### ISSUE TITLE
ldap sync copy failed

### ISSUE THREAD

**Issue by NoobAdmin430** [philbertphotos/osticket-multildap-auth#25] opened 2019-01-22 18:46 UTC
I have installed the plugin and did the setup, however, osTicket log keeps showing "ldap sync copy failed" when I mouse over the error it says "C:\xampp\htdocs\{sitename}\include\plugins\mult-ldap/sync_mldap.php"

I have opened the error logs for PHP and get the following:

[Tue Jan 22 10:33:34.924007 2019] [:error] [pid 3036:tid 1972] [client ::1:59067] PHP Warning:  include_once(C:/xampp/htdocs/Support/include/scp/sync_mldap.php): failed to open stream: No such file or directory in C:\\xampp\\htdocs\\Support\\include\\plugins\\multi-ldap\\auth.php on line 68, referer: http://localhost/support/scp/index.php

[Tue Jan 22 10:33:34.924007 2019] [:error] [pid 3036:tid 1972] [client ::1:59067] PHP Warning:  include_once(): Failed opening 'C:/xampp/htdocs/Support/include/scp/sync_mldap.php' for inclusion (include_path='./;C:/xampp/htdocs/Support/include/;C:/xampp/htdocs/Support/include/pear/;phar://C:/xampp/htdocs/Support/include/plugins/auth-ldap.phar/include') in C:\\xampp\\htdocs\\Support\\include\\plugins\\multi-ldap\\auth.php on line 68, referer: http://localhost/support/scp/index.php

I have tried deleting the plugin and reinstalling it and I have verified the "sync_mldap.php" file is in the /scp folder.

I'm running osTicket 1.10.4 with PHP version 5.6.39. This is running on a Windows Server 2016 box with Xampp. If you need any other information, I'm happy to provide it.

**Comment by philbertphotos** [comment] 2019-01-22 20:24
Copy "sync_mldap.php" manually to "C:/xampp/htdocs/Support/include/scp/"
It seems there is a problem with the script and windows systems. I will have to create a gracefully way to check so the plugin lets the user know what the issue is.

**Comment by NoobAdmin430** [comment] 2019-01-22 21:01
OK, so I didn't have a /include/scp directory at all so I created one and placed the file in there. The /scp directory is set as "C:/xampp/htdocs/Support/scp" by default. However, I'm getting another error message in the PHP logs now:

PHP Fatal error:  Cannot redeclare class SyncLDAPMultiClass in C:\\xampp\\htdocs\\Support\\include\\scp\\sync_mldap.php on line 507, referer: http://p1fcu-osticket.potlatch1fcu.local/support/scp/logs.php

The osTicket log is showing the same error above:

"ldap sync copy failed" when I mouse over the error it says "C:\xampp\htdocs\Support\include\plugins\mult-ldap/sync_mldap.php"

**Comment by philbertphotos** [comment] 2019-01-22 21:41
sorry its supposed to be in "C:/xampp/htdocs/Support/scp/"

**Comment by NoobAdmin430** [comment] 2019-01-22 23:44
In fact the more and more I look at things I think my issue and issue #24 are the same. I don't mean to make it seem like I know what is going on, just trying to help in any way possible. I really do appreciate the time you have placed into this and can't wait to get it working :)

**Comment by philbertphotos** [comment] 2019-01-23 02:09
Will look at the code and maybe do a windows install to see why it messes up on windows. Bother me all you like its a good thing becasue I want to get rid of these stupid bugs.

**Comment by NoobAdmin430** [comment] 2019-01-23 17:36
OK, I messed with this for about 8 hours for as much as I understand PHP (which isn't a lot) and I cannot get past the error:

PHP Fatal error: Cannot redeclare class SyncLDAPMultiClass in C:\xampp\htdocs\Support\include\scp\sync_mldap.php on line 507, referer: http://{Server}/support/scp/logs.php

I'm not sure what's going on, but hopefully you or someone more proficient in PHP can figure it out.

**Comment by niphint** [comment] 2019-02-14 08:12
Here is what I did:
auth.php, from row 268:

> 	function loadSync() {
> 	$sql = 'SELECT * FROM ' . PLUGIN_TABLE . ' WHERE isactive=1 AND id=' . db_input($this->getId());
> 		$source = MULTI_PLUGIN_ROOT . 'sync_mldap.php';
> 		//$file = $_SERVER["DOCUMENT_ROOT"] . OST_WEB_ROOT . 'scp/sync_mldap.php';
> 		$file = 'C:\xampp\htdocs\helpdesk\include\plugins\multi-ldap\sync_mldap.php';

I commented the $file out, there is something wrong with that. it has to lead to the plugin sync_mldap.
After that everything worked.

**Comment by NoobAdmin430** [comment] 2019-02-21 23:16
niphint,

I tried what you suggested and while I'm no longer getting any error messages, I'm also not getting the sync to work at all. It is not showing that the sync completed or even attempted to run in the logs.

**Comment by niphint** [comment] 2019-05-09 06:20
Did you found a solution @NoobAdmin430  ?

**Comment by philbertphotos** [comment] 2020-10-14 12:41
Is this still an issue with the updates?

**Comment by philbertphotos** [comment] 2020-11-05 13:26
This has been fixed with the new version I suggest you update.

**Closed by philbertphotos** 2020-11-05 13:26 UTC
